---
triple:          'x86_64-apple-darwin'
binary-path:     "/Users/zzuniy/Documents/한동대학교/2025/데이타구조/exam/midterm/02.arrayStack/stack"
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: __ZN5StackC2Ev, symObjAddr: 0x0, symBinAddr: 0x100000DE0, symSize: 0x20 }
  - { offsetInCU: 0x2EBD, offset: 0x2EBD, size: 0x8, addend: 0x0, symName: __ZN5StackC2Ev, symObjAddr: 0x0, symBinAddr: 0x100000DE0, symSize: 0x20 }
  - { offsetInCU: 0x2EE6, offset: 0x2EE6, size: 0x8, addend: 0x0, symName: __ZN5StackC1Ev, symObjAddr: 0x20, symBinAddr: 0x100000E00, symSize: 0x20 }
  - { offsetInCU: 0x2F0F, offset: 0x2F0F, size: 0x8, addend: 0x0, symName: __ZN5Stack4pushEi, symObjAddr: 0x40, symBinAddr: 0x100000E20, symSize: 0x60 }
  - { offsetInCU: 0x2F42, offset: 0x2F42, size: 0x8, addend: 0x0, symName: __ZN5Stack7is_fullEv, symObjAddr: 0xA0, symBinAddr: 0x100000E80, symSize: 0x30 }
  - { offsetInCU: 0x2F67, offset: 0x2F67, size: 0x8, addend: 0x0, symName: __ZN5Stack3popEv, symObjAddr: 0xD0, symBinAddr: 0x100000EB0, symSize: 0x50 }
  - { offsetInCU: 0x2F8C, offset: 0x2F8C, size: 0x8, addend: 0x0, symName: __ZN5Stack8is_emptyEv, symObjAddr: 0x120, symBinAddr: 0x100000F00, symSize: 0x40 }
  - { offsetInCU: 0x2FB1, offset: 0x2FB1, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x160, symBinAddr: 0x100000F40, symSize: 0x57 }
...
